const makeQ = (q, opts, c) => ({ q, opts, c });

window.QUESTION_BATCHES = {
  easy: [
    // ── APODOS DE JUGADORES ──
    makeQ("What is Lionel Messi's nickname?", ["La Pulga", "El Pibe", "El Bicho", "La Bestia"], 0),
    makeQ("What is Cristiano Ronaldo's nickname?", ["CR10", "CR7", "El Rey", "O Fenomeno"], 1),
    makeQ("What is Javier Hernandez's nickname?", ["El Piojo", "El Matador", "Chicharito", "El Chino"], 2),
    makeQ("What is Ronaldo Nazario's nickname?", ["O Rei", "El Fenomeno", "La Fiera", "Ronaldão"], 1),
    makeQ("What is Neymar's nickname?", ["Ney", "O Bruxo", "Juninho", "Neymarzinho"], 0),
    makeQ("What is Kylian Mbappe's nickname?", ["The Rocket", "Donatello", "The Kid", "K10"], 1),
    makeQ("What is Diego Maradona's nickname?", ["El Pibe de Oro", "El Diez", "El Rey", "Marado"], 0),
    makeQ("What is Zlatan Ibrahimovic's nickname?", ["Ibra", "The Lion", "El Sueco", "Zlatanator"], 0),
    makeQ("What is Andres Guardado's nickname?", ["El Principe", "El Capitan", "El Tigre", "El Lider"], 0),
    makeQ("What is Guillermo Ochoa's nickname?", ["El Memo", "El Muro", "La Araña", "El Portero"], 0),
    makeQ("What is Hirving Lozano's nickname?", ["El Chucky", "El Rapido", "El Feo", "El Patas"], 0),
    makeQ("What is Alexis Vega's nickname?", ["El Conejo", "El Ratón", "El Lobo", "El Gato"], 0),
    makeQ("What is Hugo Sanchez's nickname?", ["El Hugol", "El Rey del Gol", "El Bombardero", "El Nueve"], 0),
    makeQ("What is Cuauhtemoc Blanco's nickname?", ["El Cuau", "El Mago", "El Diez", "El Viejo"], 0),
    makeQ("What is Erling Haaland's nickname?", ["The Terminator", "The Cyborg", "The Viking", "El Nórdico"], 1),
    makeQ("What is Mohamed Salah's nickname?", ["The Egyptian King", "The Pharaoh", "Mo", "El Halcon"], 0),
    makeQ("What is Robert Lewandowski's nickname?", ["Lewy", "The Polish Sniper", "El Polaco", "The Machine"], 0),
    makeQ("What is Gianluigi Buffon's nickname?", ["Gigi", "The Wall", "Super Gigi", "Il Capitano"], 0),
    makeQ("What is Lamine Yamal's nickname?", ["El Niño Maravilla", "La Joya", "El Baby", "Mini Messi"], 0),
    makeQ("What is Vinicius Jr's nickname?", ["Vini Jr", "The Brazilian Wizard", "El Bailarín", "Viniciño"], 0),

    // ── CLUBES MEXICANOS ──
    makeQ("What color is Club America's home jersey?", ["Blue and white", "Red and white", "Yellow and blue", "Green and white"], 2),
    makeQ("What animal is on Club America's crest?", ["Lion", "Tiger", "Eagle", "Bull"], 2),
    makeQ("What colors does Club Chivas (Guadalajara) wear?", ["Blue and white", "Red and white with vertical stripes", "Yellow and green", "Black and red"], 1),
    makeQ("What animal is associated with Club Tigres UANL?", ["Lion", "Tiger", "Jaguar", "Puma"], 1),
    makeQ("What city is Cruz Azul from?", ["Guadalajara", "Monterrey", "Mexico City", "Puebla"], 2),
    makeQ("What city is Club Tigres from?", ["Mexico City", "Guadalajara", "Monterrey", "Tijuana"], 2),
    makeQ("What color is Cruz Azul's home jersey?", ["Red", "Blue", "Green", "Black"], 1),
    makeQ("What is the main color of Club Pumas UNAM's jersey?", ["Blue and gold", "Red and white", "Green and white", "Black and white"], 0),
    makeQ("What animal is on the Pumas UNAM crest?", ["Puma", "Jaguar", "Lion", "Panther"], 0),
    makeQ("What is the nickname of Club America?", ["Las Aguilas", "Los Toros", "Los Leones", "Las Panteras"], 0),
    makeQ("What is the nickname of Chivas de Guadalajara?", ["El Rebaño Sagrado", ["Las Cabras", "El Rebaño Sagrado", "Los Toros", "Los Carneros"]], 1),
    makeQ("Which Mexican club plays at the Estadio Azteca?", ["Chivas", "Tigres", "Club America", "Cruz Azul"], 2),
    makeQ("What city is Club Atlas from?", ["Monterrey", "Mexico City", "Guadalajara", "Puebla"], 2),
    makeQ("What colors does Monterrey (Rayados) wear?", ["Red and white", "Blue and white with stripes", "Yellow and black", "Green and gold"], 1),
    makeQ("What is the nickname of CF Monterrey?", ["Los Rayados", ["Los Tigres", "Los Rayados", "Los Bravos", "Los Gallos"]], 1),
    makeQ("What is the main color of Deportivo Toluca's jersey?", ["Red", "Blue", "Yellow", "Green"], 0),
    makeQ("Which Mexican club is known as 'Los Diablos Rojos'?", ["Cruz Azul", "Chivas", "Toluca", "Tijuana"], 2),
    makeQ("What league do Club America and Chivas play in?", ["MLS", "Liga MX", "Liga Premier", "Apertura League"], 1),
    makeQ("Which Mexican team is known as 'La Maquina'?", ["Club America", "Cruz Azul", "Tigres", "Pumas"], 1),
    makeQ("What does UANL stand for in Tigres UANL?", ["United Athletes of Northern Latin League", "Universidad Autónoma de Nuevo León", "Union of Athletes in National League", "Urban Athletics National League"], 1),

    // ── JUGADORES FAMOSOS POR PAÍS ──
    makeQ("Which famous player wore the number 10 for Brazil and is considered the greatest of all time by many?", ["Zico", "Ronaldo", "Pelé", "Ronaldinho"], 2),
    makeQ("Which player is the most famous in Argentine history and wore the number 10?", ["Gabriel Batistuta", "Diego Maradona", "Sergio Aguero", "Pablo Aimar"], 1),
    makeQ("Which famous French player won the 1998 World Cup and is known for 'Zidane'?", ["Michel Platini", "Thierry Henry", "Zinedine Zidane", "Just Fontaine"], 2),
    makeQ("Which German player is known as 'Der Kaiser' and is one of the greatest defenders ever?", ["Lothar Matthaus", "Gerd Muller", "Franz Beckenbauer", "Uwe Seeler"], 2),
    makeQ("Which Portuguese player is known as 'the Black Panther' and was a legend in the 1960s?", ["Luis Figo", "Cristiano Ronaldo", "Rui Costa", "Eusebio"], 3),
    makeQ("Which Mexican player became a legend at Real Madrid in the 1980s and 90s?", ["Cuauhtemoc Blanco", "Hugo Sanchez", "Jared Borgetti", "Luis Hernandez"], 1),
    makeQ("Which Spanish player is famous for playing for Barcelona and winning everything?", ["Fernando Torres", "Raul", "Xavi Hernandez", "David Villa"], 2),
    makeQ("Which England player is the all-time top scorer for the national team?", ["Wayne Rooney", "Harry Kane", "Gary Lineker", "Michael Owen"], 1),
    makeQ("Which Brazilian player was known as 'O Rei' (The King)?", ["Ronaldo", "Zico", "Pelé", "Garrincha"], 2),
    makeQ("Which player from Argentina is the current world champion and plays in MLS?", ["Angel Di Maria", "Sergio Aguero", "Lautaro Martinez", "Lionel Messi"], 3),
    makeQ("Which famous Dutch player played for Barcelona and introduced 'Total Football'?", ["Marco van Basten", "Ruud Gullit", "Johan Cruyff", "Frank Rijkaard"], 2),
    makeQ("Which Italian goalkeeper is considered one of the best of all time?", ["Dino Zoff", "Gianluigi Buffon", "Walter Zenga", "Angelo Peruzzi"], 1),
    makeQ("Which US player is famous for playing in MLS and the national team as a winger?", ["Clint Dempsey", "Landon Donovan", "Christian Pulisic", "Tim Howard"], 2),
    makeQ("Who is the most famous player in the history of Club America?", ["Cuauhtemoc Blanco", "Hugo Sanchez", "Luis Garcia", "Claudio Suarez"], 0),
    makeQ("Which Uruguayan striker is known for biting opponents and playing for Barcelona?", ["Edinson Cavani", "Diego Forlan", "Luis Suarez", "Carlos Tevez"], 2),

    // ── REGLAS BÁSICAS ──
    makeQ("How many players does each team have on the field in football?", ["9", "10", "11", "12"], 2),
    makeQ("How long is a standard football match?", ["80 minutes", "90 minutes", "100 minutes", "120 minutes"], 1),
    makeQ("What color card means a player is sent off?", ["Blue", "Yellow", "Red", "Black"], 2),
    makeQ("How many yellow cards make a red card in the same match?", ["1", "2", "3", "4"], 1),
    makeQ("What is awarded when a foul happens inside the penalty box?", ["Corner kick", "Free kick", "Penalty kick", "Throw-in"], 2),
    makeQ("Who is the player that stops the ball from going into the goal?", ["Striker", "Midfielder", "Defender", "Goalkeeper"], 3),
    makeQ("What happens when the ball goes out past the sideline?", ["Corner kick", "Throw-in", "Goal kick", "Free kick"], 1),
    makeQ("How many goals is a hat-trick?", ["2", "3", "4", "5"], 1),
    makeQ("What do we call 2 goals scored by the same player?", ["A double", "A brace", "A pair", "A duo"], 1),
    makeQ("What color card is shown as a warning?", ["Red", "Green", "Blue", "Yellow"], 3),
    makeQ("How many halves are in a regular football match?", ["1", "2", "3", "4"], 1),
    makeQ("When can a goalkeeper use their hands?", ["Anywhere on the field", "Only inside their own penalty area", "Only in their own half", "Never"], 1),
    makeQ("What is the name of the kick taken from the center circle to start the game?", ["Free kick", "Penalty kick", "Kick-off", "Drop ball"], 2),
    makeQ("How many substitutes can a team normally make in a match?", ["3", "4", "5", "6"], 2),
    makeQ("What is a shot that goes into the top corner of the goal often called?", ["A screamer", "A top-bins", "A worldie", "Any of these"], 3),
    makeQ("What is it called when a goalkeeper does not let in any goals?", ["A clean sheet", "A shutout", "A white game", "Both A and B"], 3),
    makeQ("Which line divides the field in half?", ["The center line", "The halfway line", "The midfield line", "The middle line"], 1),
    makeQ("How many players can be on the bench in a match?", ["5", "7", "9", "It depends on the competition"], 3),
    makeQ("What is the small box directly in front of the goal called?", ["The six-yard box", "The goalkeeper box", "The small area", "The goal box"], 0),
    makeQ("What shape is the penalty spot?", ["A circle", "A square", "A dot/point", "A cross"], 2),

    // ── ¿EN QUÉ EQUIPO JUEGA? ──
    makeQ("Which club does Lionel Messi currently play for?", ["Barcelona", "PSG", "Inter Miami", "Al Hilal"], 2),
    makeQ("Which club does Cristiano Ronaldo currently play for?", ["Manchester United", "Al Nassr", "Real Madrid", "Juventus"], 1),
    makeQ("Which club does Kylian Mbappe currently play for?", ["PSG", "Real Madrid", "Manchester City", "Arsenal"], 1),
    makeQ("Which club does Vinicius Jr play for?", ["Barcelona", "Manchester City", "Real Madrid", "PSG"], 2),
    makeQ("Which club does Erling Haaland play for?", ["Borussia Dortmund", "RB Leipzig", "Manchester City", "Bayern Munich"], 2),
    makeQ("Which club does Lamine Yamal play for?", ["Real Madrid", "Atletico Madrid", "PSG", "Barcelona"], 3),
    makeQ("Which club does Mohamed Salah play for?", ["Arsenal", "Liverpool", "Chelsea", "Manchester United"], 1),
    makeQ("Which club does Robert Lewandowski currently play for?", ["Bayern Munich", "PSG", "Barcelona", "Juventus"], 2),
    makeQ("Which club does Jude Bellingham play for?", ["Liverpool", "Manchester City", "Real Madrid", "Arsenal"], 2),
    makeQ("Which club does Pedri play for?", ["Real Madrid", "Atletico Madrid", "Barcelona", "Valencia"], 2),
    makeQ("Which club does Hirving 'Chucky' Lozano play for?", ["PSV", "Napoli", "San Diego FC", "Monterrey"], 2),
    makeQ("Which club does Guillermo Ochoa play for?", ["Club America", "Cruz Azul", "Salernitana", "Toluca"], 0),
    makeQ("Which club does Kevin De Bruyne play for?", ["Barcelona", "Arsenal", "Manchester City", "Inter Milan"], 2),
    makeQ("Which club does Harry Kane play for?", ["Tottenham", "Bayern Munich", "Manchester United", "PSG"], 1),
    makeQ("Which club did Ronaldo Nazario (R9) famously play for in Brazil?", ["Flamengo", "Corinthians", "Santos", "Cruzeiro"], 1),

    // ── ¿DE QUÉ CIUDAD ES ESTE EQUIPO? ──
    makeQ("What city is Real Madrid from?", ["Barcelona", "Seville", "Valencia", "Madrid"], 3),
    makeQ("What city is FC Barcelona from?", ["Madrid", "Seville", "Barcelona", "Bilbao"], 2),
    makeQ("What city is Manchester United from?", ["London", "Liverpool", "Manchester", "Leeds"], 2),
    makeQ("What city is Liverpool FC from?", ["Manchester", "Birmingham", "London", "Liverpool"], 3),
    makeQ("What city is Club America from?", ["Guadalajara", "Monterrey", "Puebla", "Mexico City"], 3),
    makeQ("What city is Club Chivas (Guadalajara) from?", ["Mexico City", "Monterrey", "Guadalajara", "Tijuana"], 2),
    makeQ("What city is Tigres UANL from?", ["Guadalajara", "Mexico City", "Tijuana", "Monterrey"], 3),
    makeQ("What city is Cruz Azul from?", ["Monterrey", "Guadalajara", "Mexico City", "Puebla"], 2),
    makeQ("What city is Pumas UNAM from?", ["Guadalajara", "Mexico City", "Monterrey", "Toluca"], 1),
    makeQ("What city is Bayern Munich from?", ["Berlin", "Hamburg", "Frankfurt", "Munich"], 3),
    makeQ("What city is Juventus from?", ["Rome", "Milan", "Naples", "Turin"], 3),
    makeQ("What city is Paris Saint-Germain (PSG) from?", ["Lyon", "Marseille", "Paris", "Bordeaux"], 2),
    makeQ("What city is Boca Juniors from?", ["Montevideo", "Santiago", "Rio de Janeiro", "Buenos Aires"], 3),
    makeQ("What city is CF Monterrey (Rayados) from?", ["Mexico City", "Guadalajara", "Monterrey", "Tijuana"], 2),
    makeQ("What city is Atlas FC from?", ["Mexico City", "Monterrey", "Puebla", "Guadalajara"], 3),

    // ── ¿EN QUÉ EQUIPO JUGABA? ──
    makeQ("Which club did Lionel Messi spend most of his career at before leaving in 2021?", ["Real Madrid", "PSG", "Barcelona", "Juventus"], 2),
    makeQ("Which club did Cristiano Ronaldo first become world-famous at?", ["Sporting CP", "Juventus", "Manchester City", "Manchester United"], 3),
    makeQ("Which club did Diego Maradona play for during his best years in Europe?", ["Real Madrid", "Juventus", "Napoli", "Inter Milan"], 2),
    makeQ("Which Mexican club did Hugo Sanchez play for before going to Real Madrid?", ["Chivas", "Cruz Azul", "Club America", "UNAM Pumas"], 3),
    makeQ("Which club did Ronaldinho play for at the peak of his career?", ["Real Madrid", "PSG", "Barcelona", "AC Milan"], 2),
    makeQ("Which club did Zinedine Zidane play for most of his career in Spain?", ["Barcelona", "Atletico Madrid", "Valencia", "Real Madrid"], 3),
    makeQ("Which club did David Beckham make famous in England?", ["Arsenal", "Liverpool", "Chelsea", "Manchester United"], 3),
    makeQ("Which club did Pele play almost his entire career at?", ["Flamengo", "Corinthians", "Santos", "Vasco da Gama"], 2),
    makeQ("Which club did Thierry Henry become a legend at in England?", ["Chelsea", "Arsenal", "Manchester United", "Liverpool"], 1),
    makeQ("Which club did Cuauhtemoc Blanco play most of his Liga MX career at?", ["Pumas", "Cruz Azul", "Chivas", "Club America"], 3),
    makeQ("Which club did Chicharito (Javier Hernandez) play for in England?", ["Arsenal", "Liverpool", "Chelsea", "Manchester United"], 3),
    makeQ("Which club did Neymar play for before PSG?", ["Santos", "Barcelona", "Real Madrid", "Manchester City"], 1),
    makeQ("Which club did Johan Cruyff become a legend at?", ["PSV", "Ajax", "Feyenoord", "Juventus"], 1),
    makeQ("Which club did Andres Iniesta spend most of his career at?", ["Real Madrid", "Valencia", "Barcelona", "Atletico Madrid"], 2),
    makeQ("Which club did Gareth Bale play for in Spain?", ["Atletico Madrid", "Sevilla", "Barcelona", "Real Madrid"], 3),

    // ── FÚTBOL GENERAL MUY FÁCIL ──
    makeQ("Which country has won the most men's World Cups?", ["Germany", "Italy", "Brazil", "Argentina"], 2),
    makeQ("Who won the 2022 FIFA World Cup?", ["France", "Brazil", "Argentina", "Germany"], 2),
    makeQ("What country is Lionel Messi from?", ["Spain", "Uruguay", "Argentina", "Chile"], 2),
    makeQ("What country is Cristiano Ronaldo from?", ["Brazil", "Spain", "Italy", "Portugal"], 3),
    makeQ("What country is Kylian Mbappe from?", ["Belgium", "France", "Cameroon", "Algeria"], 1),
    makeQ("What country is Neymar from?", ["Argentina", "Portugal", "Colombia", "Brazil"], 3),
    makeQ("Which club plays at the Santiago Bernabeu stadium?", ["Barcelona", "Atletico Madrid", "Sevilla", "Real Madrid"], 3),
    makeQ("Which club plays at Camp Nou?", ["Real Madrid", "Atletico Madrid", "Barcelona", "Valencia"], 2),
    makeQ("Which club plays at Old Trafford?", ["Liverpool", "Manchester City", "Arsenal", "Manchester United"], 3),
    makeQ("What color is the Brazil national team's home jersey?", ["Green", "Blue", "Yellow", "White"], 2),
    makeQ("What color is Argentina's home jersey?", ["Red and white", "Blue and white stripes", "Yellow and green", "All white"], 1),
    makeQ("What color is Germany's traditional home jersey?", ["Red", "Black", "White", "Blue"], 2),
    makeQ("How many teams play in the FIFA World Cup since 2026?", ["32", "40", "48", "64"], 2),
    makeQ("In which three countries is the 2026 World Cup hosted?", ["Mexico, Brazil, Argentina", "Mexico, USA, Canada", "USA, Canada, Colombia", "Mexico, USA, Spain"], 1),
    makeQ("Which stadium has hosted the most World Cup matches in Mexico?", ["Estadio Jalisco", "Estadio BBVA", "Estadio Azteca", "Estadio Akron"], 2),
    makeQ("What is the national team of Mexico nicknamed?", ["La Roja", "El Tri", "La Verde", "Los Aztecas"], 1),
    makeQ("What does FIFA stand for?", ["Football International Federation of America", "Fédération Internationale de Football Association", "Football Integrated Federation Agency", "Federal International Football Arena"], 1),
    makeQ("What is the name of the Champions League trophy?", ["The Big Cup", "The Golden Cup", "The European Cup", "The Champions Cup"], 2),
    makeQ("In football, what does a player do with a 'bicycle kick'?", ["Kick the ball backwards while in the air", "Run fast like pedaling", "Kick with both feet", "Spin and kick"], 0),
    makeQ("Which famous football event happens every 4 years?", ["Copa America", "The World Cup", "The Olympics", "The Champions League"], 1),
  ],
  medium: [
    makeQ("Who scored the winning goal in the 2010 World Cup final?", ["David Villa", "Andres Iniesta", "Xavi", "Fernando Torres"], 1),
    makeQ("Which player scored a hat-trick in the 2022 World Cup final?", ["Lionel Messi", "Julian Alvarez", "Kylian Mbappe", "Antoine Griezmann"], 2),
    makeQ("Which country hosted the 2010 FIFA World Cup?", ["Egypt", "South Africa", "Morocco", "Nigeria"], 1),
    makeQ("Who was captain of Argentina in the 2022 World Cup final?", ["Lionel Messi", "Angel Di Maria", "Nicolas Otamendi", "Rodrigo De Paul"], 0),
    makeQ("Which club did Cristiano Ronaldo first represent professionally?", ["Porto", "Benfica", "Sporting CP", "Braga"], 2),
    makeQ("Which nation eliminated Mexico at the 2018 World Cup?", ["Germany", "Brazil", "Sweden", "Belgium"], 1),
    makeQ("How many World Cup titles has Italy won?", ["2", "3", "4", "5"], 2),
    makeQ("Which player holds the record for most men's World Cup goals?", ["Pele", "Ronaldo", "Miroslav Klose", "Lionel Messi"], 2),
    makeQ("Who won the Ballon d'Or in 2023?", ["Erling Haaland", "Kylian Mbappe", "Lionel Messi", "Kevin De Bruyne"], 2),
    makeQ("Which club has won the most UEFA Champions League titles?", ["AC Milan", "Liverpool", "Bayern Munich", "Real Madrid"], 3),
    makeQ("Which nation was runner-up in the 2018 World Cup?", ["Belgium", "England", "Croatia", "Argentina"], 2),
    makeQ("Which nation won the 2014 FIFA World Cup?", ["Argentina", "Germany", "Netherlands", "Brazil"], 1),
    makeQ("Which player scored the famous 'Hand of God' goal?", ["Pele", "Zico", "Diego Maradona", "Jorge Valdano"], 2),
    makeQ("Which club is known as 'Los Blancos'?", ["Sevilla", "Real Madrid", "Valencia", "Atletico Madrid"], 1),
    makeQ("How many men's World Cups has Argentina won?", ["2", "3", "4", "5"], 1),
    makeQ("How many men's World Cups has Germany won?", ["2", "3", "4", "5"], 2),
    makeQ("Which player is the all-time top scorer in UEFA Champions League history?", ["Lionel Messi", "Cristiano Ronaldo", "Robert Lewandowski", "Karim Benzema"], 1),
    makeQ("Which club did Hugo Sanchez become a legend with in Spain?", ["Barcelona", "Valencia", "Real Madrid", "Sevilla"], 2),
    makeQ("What is the nickname of the Mexican national team?", ["La Roja", "El Tri", "La Celeste", "The Canaries"], 1),
    makeQ("Which goalkeeper won the Golden Glove at the 2022 men's World Cup?", ["Hugo Lloris", "Emiliano Martinez", "Dominik Livakovic", "Yassine Bounou"], 1),
    makeQ("Which player scored Spain's winner in the 2010 World Cup final?", ["David Villa", "Andres Iniesta", "Xavi", "Fernando Torres"], 1),
    makeQ("Who scored the winning goal in the 2014 World Cup final?", ["Mario Gotze", "Thomas Muller", "Miroslav Klose", "Andre Schurrle"], 0),
    makeQ("Which country hosted the 1986 FIFA World Cup?", ["Argentina", "Mexico", "Spain", "Colombia"], 1),
    makeQ("Which team defeated Brazil 7-1 in the 2014 World Cup semifinal?", ["Argentina", "Germany", "Netherlands", "France"], 1),
    makeQ("Which player is known as 'El Fenomeno'?", ["Romario", "Ronaldo Nazario", "Ronaldinho", "Rivaldo"], 1),
    makeQ("Which nation won Copa America 2024?", ["Brazil", "Colombia", "Argentina", "Uruguay"], 2),
    makeQ("Which nation won UEFA Euro 2024?", ["France", "Spain", "England", "Germany"], 1),
    makeQ("Which nation won the 2022 UEFA Champions League final?", ["Liverpool", "Real Madrid", "Manchester City", "Bayern Munich"], 1),
    makeQ("Which country hosted the 2018 FIFA World Cup?", ["Russia", "Germany", "Poland", "Ukraine"], 0),
    makeQ("Which nation won UEFA Euro 2020?", ["England", "Italy", "Spain", "Denmark"], 1),
    makeQ("Who won the Golden Boot at the 2018 World Cup?", ["Harry Kane", "Kylian Mbappe", "Romelu Lukaku", "Antoine Griezmann"], 0),
    makeQ("Who won the Golden Boot at the 2022 men's World Cup?", ["Lionel Messi", "Julian Alvarez", "Kylian Mbappe", "Olivier Giroud"], 2),
    makeQ("Which nation reached the semifinals of 2022 World Cup as the first African team to do so?", ["Senegal", "Morocco", "Ghana", "Cameroon"], 1),
    makeQ("Which nation won the 2023 CONCACAF Gold Cup?", ["United States", "Canada", "Mexico", "Panama"], 2),
    makeQ("Which club is known as 'The Old Lady'?", ["Inter", "Milan", "Juventus", "Roma"], 2),
    makeQ("Which nation won the 1998 FIFA World Cup?", ["Brazil", "France", "Croatia", "Italy"], 1),
  ],
  hard: [
    makeQ("Who scored the only goal in the 1990 World Cup final?", ["Lothar Matthaus", "Andreas Brehme", "Rudi Voller", "Jurgen Klinsmann"], 1),
    makeQ("Which nation won the 1992 UEFA European Championship?", ["Germany", "Netherlands", "Denmark", "Sweden"], 2),
    makeQ("Which club won the first European Cup in 1956?", ["Benfica", "Real Madrid", "Milan", "Reims"], 1),
    makeQ("Who was the coach of Spain at the 2010 World Cup?", ["Vicente del Bosque", "Luis Aragones", "Pep Guardiola", "Rafael Benitez"], 0),
    makeQ("Which player won the 2006 World Cup Golden Ball?", ["Fabio Cannavaro", "Andrea Pirlo", "Zinedine Zidane", "Gianluigi Buffon"], 2),
    makeQ("Which nation won the 1930 World Cup?", ["Argentina", "Brazil", "Uruguay", "Italy"], 2),
    makeQ("Who scored the winner for West Germany in the 1974 World Cup final?", ["Gerd Muller", "Paul Breitner", "Uli Hoeness", "Franz Beckenbauer"], 0),
    makeQ("Which player won the Golden Boot at the 1982 World Cup?", ["Paolo Rossi", "Karl-Heinz Rummenigge", "Zico", "Socrates"], 0),
    makeQ("Which player scored nine goals at the 1966 World Cup?", ["Pele", "Eusebio", "Bobby Charlton", "Helmut Haller"], 1),
    makeQ("Which nation won the 1988 UEFA European Championship?", ["Netherlands", "Soviet Union", "West Germany", "Italy"], 0),
    makeQ("Who scored the winning goal for France in Euro 2000 final?", ["Thierry Henry", "David Trezeguet", "Zinedine Zidane", "Sylvain Wiltord"], 1),
    makeQ("Who coached Germany to the 2014 World Cup title?", ["Jurgen Klinsmann", "Joachim Low", "Hansi Flick", "Rudi Voller"], 1),
    makeQ("Who was the top scorer at the 1970 World Cup?", ["Pele", "Jairzinho", "Gerd Muller", "Tostao"], 2),
    makeQ("Who was the captain of Italy in the 2006 World Cup final?", ["Fabio Cannavaro", "Francesco Totti", "Gianluigi Buffon", "Alessandro Del Piero"], 0),
    makeQ("Who scored Germany's winning goal in Euro 1996 final?", ["Jurgen Klinsmann", "Oliver Bierhoff", "Matthias Sammer", "Stefan Kuntz"], 1),
    makeQ("Which nation did Portugal beat to win Euro 2016?", ["Germany", "France", "Spain", "Belgium"], 1),
    makeQ("Who scored Portugal's winning goal in the Euro 2016 final?", ["Cristiano Ronaldo", "Nani", "Eder", "Joao Mario"], 2),
    makeQ("Which club won the 1999 UEFA Champions League final in stoppage time?", ["Bayern Munich", "Manchester United", "Juventus", "Milan"], 1),
    makeQ("Who scored the famous volley for Real Madrid in the 2002 Champions League final?", ["Raul", "Luis Figo", "Zinedine Zidane", "Roberto Carlos"], 2),
    makeQ("Who was known as 'Der Kaiser'?", ["Gerd Muller", "Franz Beckenbauer", "Lothar Matthaus", "Sepp Maier"], 1),
    makeQ("Who won the Ballon d'Or in 1995, becoming the first African winner?", ["George Weah", "Abedi Pele", "Roger Milla", "Samuel Eto'o"], 0),
    makeQ("Which club did Johan Cruyff make famous with 'Total Football' as a player?", ["PSV", "Ajax", "Feyenoord", "AZ"], 1),
    makeQ("Which nation beat the Netherlands in the 2010 World Cup final?", ["Germany", "Spain", "Brazil", "Uruguay"], 1),
    makeQ("Who managed Porto to the 2004 Champions League title?", ["Jose Mourinho", "Carlo Ancelotti", "Rafa Benitez", "Guus Hiddink"], 0),
    makeQ("Which player holds the record for most international caps in men's football?", ["Cristiano Ronaldo", "Sergio Ramos", "Ahmed Hassan", "Bader Al-Mutawa"], 3),
    makeQ("What was the final score of the 'Match of the Century' in the 1970 World Cup semifinal?", ["4-3 to Italy", "3-2 to West Germany", "4-2 to Brazil", "3-1 to Italy"], 0),
    makeQ("Who scored the winning penalty in the 2006 World Cup final shootout?", ["Fabio Grosso", "Andrea Pirlo", "Daniele De Rossi", "Alessandro Del Piero"], 0),
    makeQ("Who was the youngest player to score in a World Cup final?", ["Pele", "Kylian Mbappe", "Michael Owen", "Diego Maradona"], 0),
    makeQ("Which nation won the 1960 inaugural European Championship?", ["Soviet Union", "Yugoslavia", "Spain", "France"], 0),
    makeQ("Who scored the decisive goal in the 1950 World Cup Maracanazo?", ["Juan Schiaffino", "Alcides Ghiggia", "Obdulio Varela", "Julio Perez"], 1),
  ]
};
