const makeQ = (q, opts, c) => ({ q, opts, c });

window.QUESTION_BATCHES = {
  easy: [
    makeQ("Which country won the 2022 FIFA World Cup?", ["France", "Brazil", "Argentina", "Germany"], 2),
    makeQ("How many players from one team are on the field in a standard match?", ["9", "10", "11", "12"], 2),
    makeQ("What body organizes the FIFA World Cup?", ["UEFA", "FIFA", "CONMEBOL", "The IOC"], 1),
    makeQ("Which country has won the most men's World Cups?", ["Germany", "Italy", "Brazil", "Argentina"], 2),
    makeQ("What is awarded when a player is caught offside?", ["A penalty", "A throw-in", "An indirect free kick", "A corner"], 2),
    makeQ("How long is a standard football match?", ["80 minutes", "90 minutes", "100 minutes", "120 minutes"], 1),
    makeQ("What color card means a player is sent off?", ["Blue", "Red", "Green", "Black"], 1),
    makeQ("Which country hosted the 2014 FIFA World Cup?", ["South Africa", "Brazil", "Russia", "Qatar"], 1),
    makeQ("Which country hosted the 2022 FIFA World Cup?", ["Qatar", "Russia", "United Arab Emirates", "Saudi Arabia"], 0),
    makeQ("Which team plays at Anfield?", ["Chelsea", "Liverpool", "Arsenal", "Everton"], 1),
    makeQ("Which club is known as FC Barcelona?", ["Barca", "Boca", "Benfica", "Braga"], 0),
    makeQ("What shape is a football goal frame?", ["Triangle", "Rectangle", "Circle", "Hexagon"], 1),
    makeQ("How many points is a win worth in most league tables?", ["1", "2", "3", "4"], 2),
    makeQ("Which nation won the 2018 FIFA World Cup?", ["Croatia", "France", "Belgium", "Brazil"], 1),
    makeQ("Who is famous for the nickname 'CR7'?", ["Kaka", "Cristiano Ronaldo", "Ronaldo Nazario", "Rivaldo"], 1),
    makeQ("Which country is Lionel Messi from?", ["Spain", "Uruguay", "Argentina", "Chile"], 2),
    makeQ("Which country is Cristiano Ronaldo from?", ["Portugal", "Brazil", "Spain", "Italy"], 0),
    makeQ("How many halves are in a football match?", ["2", "3", "4", "5"], 0),
    makeQ("What is the usual number on the back of a goalkeeper?", ["1", "4", "7", "10"], 0),
    makeQ("What is the name of the main European club competition?", ["Europa Cup", "Champions League", "Super League", "Club World Shield"], 1),
    makeQ("Which country won UEFA Euro 2024?", ["France", "Spain", "England", "Germany"], 1),
    makeQ("Which team is known as 'La Albiceleste'?", ["Spain", "Argentina", "Uruguay", "Italy"], 1),
    makeQ("What does VAR stand for?", ["Video Assistant Referee", "Verified Action Review", "Virtual Assistant Referee", "Video Appeal Room"], 0),
    makeQ("How many teams play in a match?", ["2", "3", "4", "5"], 0),
    makeQ("Which team won the first men's World Cup in 1930?", ["Argentina", "Brazil", "Uruguay", "Italy"], 2),
    makeQ("Which country won the 2010 FIFA World Cup?", ["Netherlands", "Spain", "Germany", "Brazil"], 1),
    makeQ("What restart is awarded when the ball crosses the touchline off a defender?", ["Corner kick", "Goal kick", "Penalty", "Drop ball"], 0),
    makeQ("What restart is awarded after a foul inside the penalty area?", ["Free kick", "Throw-in", "Penalty kick", "Corner"], 2),
    makeQ("How many goals is a hat-trick?", ["2", "3", "4", "5"], 1),
    makeQ("Which country won the women's 2023 FIFA World Cup?", ["England", "Spain", "United States", "Germany"], 1),
    makeQ("Which club is based at the Santiago Bernabeu?", ["Atletico Madrid", "Sevilla", "Real Madrid", "Valencia"], 2),
    makeQ("Which club is based at Old Trafford?", ["Liverpool", "Manchester United", "Manchester City", "Celtic"], 1),
    makeQ("Which player is nicknamed 'La Pulga'?", ["Sergio Aguero", "Andres Iniesta", "Lionel Messi", "Angel Di Maria"], 2),
    makeQ("How many yellow cards usually lead to a red in the same match?", ["1", "2", "3", "4"], 1),
    makeQ("What is awarded to start each half from the center circle?", ["Throw-in", "Goal kick", "Kick-off", "Indirect free kick"], 2),
    makeQ("Which country won the 2006 FIFA World Cup?", ["France", "Italy", "Germany", "Brazil"], 1),
    makeQ("Which country won the 2002 FIFA World Cup?", ["Germany", "Brazil", "Argentina", "France"], 1),
    makeQ("Which country won the 1998 FIFA World Cup?", ["Brazil", "France", "Croatia", "Italy"], 1),
    makeQ("Which country won the 1994 FIFA World Cup?", ["Italy", "Brazil", "Germany", "Argentina"], 1),
    makeQ("Which country won the 1986 FIFA World Cup?", ["Argentina", "West Germany", "Brazil", "Mexico"], 0),
    makeQ("Which country won the 1970 FIFA World Cup?", ["Italy", "Brazil", "West Germany", "England"], 1),
    makeQ("What is the area in front of goal called?", ["Center zone", "Penalty area", "Target square", "Keeper box only"], 1),
    makeQ("Which famous Mexican stadium has hosted multiple World Cups?", ["Estadio Jalisco", "Estadio BBVA", "Estadio Azteca", "Estadio Akron"], 2),
    makeQ("What color are football pitch lines usually painted?", ["Blue", "Yellow", "White", "Green"], 2),
    makeQ("Which foot is Diego Maradona most associated with?", ["Left", "Right", "Both equally", "Neither"], 0),
    makeQ("Which country is Neymar from?", ["Brazil", "Portugal", "Colombia", "Argentina"], 0),
    makeQ("Which country is Kylian Mbappe from?", ["Belgium", "France", "Cameroon", "Algeria"], 1),
    makeQ("Which team is known as 'The Reds' in England?", ["Arsenal", "Liverpool", "West Ham", "Nottingham Forest"], 1),
    makeQ("Who protects the goal?", ["Striker", "Referee", "Goalkeeper", "Captain"], 2),
    makeQ("How many referees are usually on the field of play?", ["1", "2", "3", "4"], 0),
    makeQ("Which country won Copa America 2024?", ["Brazil", "Colombia", "Argentina", "Uruguay"], 2),
    makeQ("What is a 0-0 scoreline commonly called?", ["A blank", "A clean sheet", "A goalless draw", "A dead match"], 2),
    makeQ("Which nation won the 1966 FIFA World Cup?", ["England", "West Germany", "Brazil", "Portugal"], 0),
    makeQ("How many goals is a brace?", ["1", "2", "3", "4"], 1),
    makeQ("What is shown by assistant referees to signal decisions?", ["A whistle", "A flag", "A card", "A board"], 1),
    makeQ("Which team normally kicks off the match?", ["The home team", "The away team", "The team that wins the toss", "The team in white"], 2),
    makeQ("What is the object players try to put into the goal?", ["Puck", "Ball", "Disc", "Marker"], 1),
    makeQ("Which confederation runs European football?", ["AFC", "CAF", "UEFA", "CONCACAF"], 2),
    makeQ("Which country is the United States part of in football confederation terms?", ["UEFA", "CONMEBOL", "CONCACAF", "CAF"], 2),
    makeQ("Which country won the 1958 FIFA World Cup?", ["Brazil", "Sweden", "France", "West Germany"], 0),
    makeQ("What is awarded when the goalkeeper carries the ball over the goal line?", ["Throw-in", "Goal kick", "Corner kick", "Penalty"], 2),
    makeQ("Which club is known as Bayern Munich?", ["Germany", "Bayern Munchen", "FC Basel", "Bayer Leverkusen"], 1),
    makeQ("Which country is Harry Kane from?", ["Ireland", "England", "Wales", "Scotland"], 1),
    makeQ("Which country is Luka Modric from?", ["Serbia", "Croatia", "Slovenia", "Bosnia and Herzegovina"], 1),
    makeQ("What is the captain allowed to wear?", ["A special boot", "An armband", "A different shirt color", "A headset"], 1),
    makeQ("Which player won the Golden Ball at the 2022 men's World Cup?", ["Kylian Mbappe", "Lionel Messi", "Antoine Griezmann", "Luka Modric"], 1),
    makeQ("How many goals did Mbappe score in the 2022 World Cup final?", ["1", "2", "3", "4"], 2),
    makeQ("Which club is based in Manchester and plays at the Etihad Stadium?", ["Manchester United", "Manchester City", "Bolton", "Leeds United"], 1),
    makeQ("Which country is famous for the club Boca Juniors?", ["Uruguay", "Argentina", "Chile", "Brazil"], 1),
    makeQ("What do players usually do before a penalty kick is taken?", ["Stand behind halfway", "Stay outside the box and arc", "Leave the field", "Change ends"], 1),
    makeQ("How many minutes of added time are typical at the end of each half?", ["1-5 minutes", "10 minutes", "15 minutes", "20 minutes"], 0),
    makeQ("What does the referee blow a whistle to indicate?", ["The start or stop of play", "A substitution only", "The end of the match only", "A goal celebration"], 0),
  ],
  medium: [
    makeQ("Who scored the winning goal in the 2010 World Cup final?", ["David Villa", "Andres Iniesta", "Xavi", "Fernando Torres"], 1),
    makeQ("Which player scored a hat-trick in the 2022 World Cup final?", ["Lionel Messi", "Julian Alvarez", "Kylian Mbappe", "Antoine Griezmann"], 2),
    makeQ("Which country hosted the 2010 FIFA World Cup?", ["Egypt", "South Africa", "Morocco", "Nigeria"], 1),
    makeQ("Who was captain of Argentina in the 2022 World Cup final?", ["Lionel Messi", "Angel Di Maria", "Nicolas Otamendi", "Rodrigo De Paul"], 0),
    makeQ("Which club did Cristiano Ronaldo first represent professionally?", ["Porto", "Benfica", "Sporting CP", "Braga"], 2),
    makeQ("Which club did Lionel Messi make his senior debut for?", ["Newell's Old Boys", "Barcelona", "PSG", "Argentina U20"], 1),
    makeQ("Which nation eliminated Mexico at the 2018 World Cup?", ["Germany", "Brazil", "Sweden", "Belgium"], 1),
    makeQ("How many World Cup titles has Italy won?", ["2", "3", "4", "5"], 2),
    makeQ("Which player holds the record for most men's World Cup goals?", ["Pele", "Ronaldo", "Miroslav Klose", "Lionel Messi"], 2),
    makeQ("How many men's World Cup goals did Miroslav Klose score?", ["14", "15", "16", "17"], 2),
    makeQ("Which nation won the 1934 FIFA World Cup?", ["Uruguay", "Italy", "Czechoslovakia", "Austria"], 1),
    makeQ("Which nation won the 1938 FIFA World Cup?", ["Hungary", "Italy", "Brazil", "France"], 1),
    makeQ("Who won the Ballon d'Or in 2023?", ["Erling Haaland", "Kylian Mbappe", "Lionel Messi", "Kevin De Bruyne"], 2),
    makeQ("Which club has won the most UEFA Champions League titles?", ["AC Milan", "Liverpool", "Bayern Munich", "Real Madrid"], 3),
    makeQ("How many stars appear above Brazil's men's crest for World Cup titles?", ["4", "5", "6", "7"], 1),
    makeQ("Which nation was runner-up in the 2018 World Cup?", ["Belgium", "England", "Croatia", "Argentina"], 2),
    makeQ("Who scored for Spain in the Euro 2024 final?", ["Lamine Yamal", "Nico Williams", "Alvaro Morata", "Rodri"], 1),
    makeQ("Which nation won the 2014 FIFA World Cup?", ["Argentina", "Germany", "Netherlands", "Brazil"], 1),
    makeQ("Which country hosted the 2018 FIFA World Cup?", ["Russia", "Germany", "Poland", "Ukraine"], 0),
    makeQ("Which player scored the famous 'Hand of God' goal?", ["Pele", "Zico", "Diego Maradona", "Jorge Valdano"], 2),
    makeQ("Which country did Diego Maradona score the 'Goal of the Century' against?", ["Brazil", "England", "Germany", "Belgium"], 1),
    makeQ("Which club is known as 'Los Blancos'?", ["Sevilla", "Real Madrid", "Valencia", "Atletico Madrid"], 1),
    makeQ("Which nation won the inaugural UEFA Nations League in 2019?", ["Portugal", "France", "Spain", "Netherlands"], 0),
    makeQ("Which nation won UEFA Euro 2016?", ["France", "Portugal", "Germany", "Spain"], 1),
    makeQ("Which nation won UEFA Euro 2012?", ["Italy", "Spain", "Germany", "Portugal"], 1),
    makeQ("Which nation won UEFA Euro 2008?", ["Germany", "Spain", "Netherlands", "Russia"], 1),
    makeQ("Which nation won Copa America 2021?", ["Brazil", "Argentina", "Uruguay", "Chile"], 1),
    makeQ("Which nation won Copa America 2019?", ["Brazil", "Argentina", "Chile", "Peru"], 0),
    makeQ("Who scored the winning goal in the 2014 World Cup final?", ["Mario Gotze", "Thomas Muller", "Miroslav Klose", "Andre Schurrle"], 0),
    makeQ("Which player scored the last penalty for Argentina in the 2022 final shootout?", ["Lionel Messi", "Paulo Dybala", "Gonzalo Montiel", "Leandro Paredes"], 2),
    makeQ("Which country was third place at the 2022 men's World Cup?", ["Morocco", "Croatia", "Netherlands", "Portugal"], 1),
    makeQ("Who won the Golden Boot at the 2022 men's World Cup?", ["Lionel Messi", "Julian Alvarez", "Kylian Mbappe", "Olivier Giroud"], 2),
    makeQ("Which nation won the 1990 FIFA World Cup?", ["Argentina", "West Germany", "Italy", "Brazil"], 1),
    makeQ("Which nation won the 1978 FIFA World Cup?", ["Argentina", "Brazil", "Netherlands", "West Germany"], 0),
    makeQ("Which nation won the 1974 FIFA World Cup?", ["Netherlands", "West Germany", "Brazil", "Poland"], 1),
    makeQ("Which nation won the 1954 FIFA World Cup?", ["Hungary", "West Germany", "Brazil", "Switzerland"], 1),
    makeQ("Which nation won the 1950 FIFA World Cup?", ["Uruguay", "Brazil", "Sweden", "Spain"], 0),
    makeQ("Which country hosted the 1986 FIFA World Cup?", ["Argentina", "Mexico", "Spain", "Colombia"], 1),
    makeQ("Which country hosted the 1970 FIFA World Cup?", ["Brazil", "Mexico", "Italy", "Spain"], 1),
    makeQ("How many men's World Cups has Argentina won?", ["2", "3", "4", "5"], 1),
    makeQ("How many men's World Cups has Germany won?", ["2", "3", "4", "5"], 2),
    makeQ("Who captained France to the 1998 World Cup title?", ["Didier Deschamps", "Zinedine Zidane", "Laurent Blanc", "Marcel Desailly"], 0),
    makeQ("Which country did Zinedine Zidane represent?", ["Algeria", "France", "Belgium", "Morocco"], 1),
    makeQ("Who won the Golden Boot at the 2014 World Cup?", ["James Rodriguez", "Thomas Muller", "Lionel Messi", "Neymar"], 0),
    makeQ("Who won the Golden Boot at the 2018 World Cup?", ["Harry Kane", "Kylian Mbappe", "Romelu Lukaku", "Antoine Griezmann"], 0),
    makeQ("Which player is the all-time top scorer in UEFA Champions League history?", ["Lionel Messi", "Cristiano Ronaldo", "Robert Lewandowski", "Karim Benzema"], 1),
    makeQ("Which club did Hugo Sanchez become a legend with in Spain?", ["Barcelona", "Valencia", "Real Madrid", "Sevilla"], 2),
    makeQ("Which nation won the 2023 CONCACAF Gold Cup?", ["United States", "Canada", "Mexico", "Panama"], 2),
    makeQ("What is the nickname of the Mexican national team?", ["La Roja", "El Tri", "La Celeste", "The Canaries"], 1),
    makeQ("Which nation won the 2021 UEFA Champions League final?", ["Chelsea", "Manchester City", "Bayern Munich", "Real Madrid"], 0),
    makeQ("Which nation won the 2022 UEFA Champions League final?", ["Liverpool", "Real Madrid", "Manchester City", "Bayern Munich"], 1),
    makeQ("Which nation won the 2023 UEFA Champions League final?", ["Inter", "Manchester City", "Real Madrid", "Napoli"], 1),
    makeQ("Which nation won the 2024 UEFA Champions League final?", ["Real Madrid", "Borussia Dortmund", "Bayern Munich", "Manchester City"], 0),
    makeQ("Which goalkeeper won the Golden Glove at the 2022 men's World Cup?", ["Hugo Lloris", "Emiliano Martinez", "Dominik Livakovic", "Yassine Bounou"], 1),
    makeQ("Which country did Luka Modric captain to the 2018 World Cup final?", ["Croatia", "Serbia", "Bosnia and Herzegovina", "Slovenia"], 0),
    makeQ("Which player is known as 'El Fenomeno'?", ["Romario", "Ronaldo Nazario", "Ronaldinho", "Rivaldo"], 1),
    makeQ("Which player famously wore number 10 for Brazil in 1970?", ["Jairzinho", "Pele", "Tostao", "Rivelino"], 1),
    makeQ("Which club is associated with the Camp Nou stadium?", ["Espanyol", "Barcelona", "Atletico Madrid", "Real Sociedad"], 1),
    makeQ("Which country hosted UEFA Euro 2020 final matches?", ["France", "England", "Italy", "Germany"], 1),
    makeQ("Which nation won UEFA Euro 2020?", ["England", "Italy", "Spain", "Denmark"], 1),
    makeQ("Who scored the winning goal in the 2021 Copa America final?", ["Lionel Messi", "Angel Di Maria", "Lautaro Martinez", "Rodrigo De Paul"], 1),
    makeQ("Which nation did Colombia defeat in the Copa America 2024 semifinal?", ["Brazil", "Uruguay", "Argentina", "Canada"], 1),
    makeQ("Which country has hosted the men's World Cup three times before 2026?", ["Germany", "Brazil", "Mexico", "France"], 2),
    makeQ("Which club did Andres Iniesta spend most of his career with?", ["Real Madrid", "Barcelona", "Valencia", "Villarreal"], 1),
    makeQ("Who was the top scorer of the 1986 World Cup?", ["Gary Lineker", "Diego Maradona", "Careca", "Emilio Butragueno"], 0),
    makeQ("Which nation won the 1962 FIFA World Cup?", ["Brazil", "Czechoslovakia", "Chile", "Uruguay"], 0),
    makeQ("Which nation won the 1958 World Cup final against Sweden?", ["France", "Brazil", "West Germany", "Uruguay"], 1),
    makeQ("Which club is known as 'The Old Lady'?", ["Inter", "Milan", "Juventus", "Roma"], 2),
    makeQ("Which country won the 2024 Olympic women's football gold medal?", ["United States", "Brazil", "Spain", "Germany"], 0),
    makeQ("Which nation reached the semifinals of the 2022 men's World Cup as the first African team to do so?", ["Senegal", "Morocco", "Ghana", "Cameroon"], 1),
    makeQ("Which player scored Spain's extra-time winner in the 2010 World Cup semifinal against Germany?", ["David Silva", "Carles Puyol", "David Villa", "Andres Iniesta"], 1),
    makeQ("Which team defeated Brazil 7-1 in the 2014 World Cup semifinal?", ["Argentina", "Germany", "Netherlands", "France"], 1),
    makeQ("Who scored a hat-trick for England against Panama in the 2018 World Cup?", ["Harry Kane", "Marcus Rashford", "John Stones", "Jesse Lingard"], 2),
    makeQ("Which nation eliminated Brazil in the quarterfinals of the 2022 World Cup?", ["Croatia", "France", "Argentina", "Morocco"], 0),
    makeQ("Which player scored 5 goals in a single World Cup match?", ["Just Fontaine", "Oleg Salenko", "Sandor Kocsis", "Gerd Muller"], 1),
    makeQ("What is the fastest goal ever scored in World Cup history?", ["11 seconds", "18 seconds", "25 seconds", "30 seconds"], 0),
    makeQ("Which player has received the most red cards in international football?", ["Gerardo Bedoya", "Sergio Ramos", "Pepe", "Vidal"], 0),
  ],
  hard: [
    makeQ("Who scored the only goal in the 1990 World Cup final?", ["Lothar Matthaus", "Andreas Brehme", "Rudi Voller", "Jurgen Klinsmann"], 1),
    makeQ("Which nation won the 1954 World Cup after defeating Hungary in the final?", ["Brazil", "Uruguay", "West Germany", "Austria"], 2),
    makeQ("Who scored in extra time for France in the 1984 Euro final?", ["Michel Platini", "Alain Giresse", "Jean Tigana", "Luis Fernandez"], 0),
    makeQ("Which nation won the 1992 UEFA European Championship?", ["Germany", "Netherlands", "Denmark", "Sweden"], 2),
    makeQ("Which club won the first European Cup in 1956?", ["Benfica", "Real Madrid", "Milan", "Reims"], 1),
    makeQ("Who was the coach of Spain at the 2010 World Cup?", ["Vicente del Bosque", "Luis Aragones", "Pep Guardiola", "Rafael Benitez"], 0),
    makeQ("Which nation did Italy beat in the 1982 World Cup final?", ["Brazil", "Argentina", "West Germany", "France"], 2),
    makeQ("Who scored all three goals for England in the 1966 World Cup final?", ["Geoff Hurst", "Bobby Charlton", "Martin Peters", "Jimmy Greaves"], 0),
    makeQ("Which player won the 2006 World Cup Golden Ball?", ["Fabio Cannavaro", "Andrea Pirlo", "Zinedine Zidane", "Gianluigi Buffon"], 2),
    makeQ("Which nation did Uruguay beat in the 1930 World Cup final?", ["Brazil", "Argentina", "Chile", "United States"], 1),
    makeQ("Who scored the winning goal in the 1974 World Cup final for West Germany?", ["Gerd Muller", "Paul Breitner", "Uli Hoeness", "Franz Beckenbauer"], 0),
    makeQ("Which nation won the 1962 World Cup final against Czechoslovakia?", ["Brazil", "Chile", "Yugoslavia", "Spain"], 0),
    makeQ("Which player won the Golden Boot at the 1982 World Cup?", ["Paolo Rossi", "Karl-Heinz Rummenigge", "Zico", "Socrates"], 0),
    makeQ("Which player scored nine goals at the 1966 World Cup?", ["Pele", "Eusebio", "Bobby Charlton", "Helmut Haller"], 1),
    makeQ("Which club did Alfredo Di Stefano star for in Europe?", ["Barcelona", "Real Madrid", "Juventus", "Inter"], 1),
    makeQ("Which nation won the 1988 UEFA European Championship?", ["Netherlands", "Soviet Union", "West Germany", "Italy"], 0),
    makeQ("Who scored the winning goal for France in the Euro 2000 final?", ["Thierry Henry", "David Trezeguet", "Zinedine Zidane", "Sylvain Wiltord"], 1),
    makeQ("Which nation won the 1976 UEFA European Championship?", ["Czechoslovakia", "West Germany", "Netherlands", "Yugoslavia"], 0),
    makeQ("What famous penalty technique is named after Antonin Panenka?", ["Driven penalty", "Chip penalty", "Side-foot penalty", "Knuckleball penalty"], 1),
    makeQ("Who coached Germany to the 2014 World Cup title?", ["Jurgen Klinsmann", "Joachim Low", "Hansi Flick", "Rudi Voller"], 1),
    makeQ("Which nation did Spain defeat in the Euro 2012 final by four goals?", ["Portugal", "Germany", "Italy", "France"], 2),
    makeQ("Who was the top scorer at the 1970 World Cup?", ["Pele", "Jairzinho", "Gerd Muller", "Tostao"], 2),
    makeQ("Which player scored for the Netherlands in the 2010 World Cup semifinal against Uruguay?", ["Arjen Robben", "Wesley Sneijder", "Robin van Persie", "Dirk Kuyt"], 1),
    makeQ("Which nation won the African Cup of Nations in 2021, played in 2022?", ["Egypt", "Senegal", "Algeria", "Morocco"], 1),
    makeQ("Who was the captain of Italy in the 2006 World Cup final?", ["Fabio Cannavaro", "Francesco Totti", "Gianluigi Buffon", "Alessandro Del Piero"], 0),
    makeQ("Which nation won the 1980 UEFA European Championship?", ["West Germany", "Belgium", "Italy", "Czechoslovakia"], 0),
    makeQ("Which goalkeeper captained Spain to the 2010 World Cup title?", ["Pepe Reina", "Victor Valdes", "Iker Casillas", "David de Gea"], 2),
    makeQ("Who scored the opening goal in the 1998 World Cup final?", ["Zinedine Zidane", "Emmanuel Petit", "Youri Djorkaeff", "Didier Deschamps"], 0),
    makeQ("Which nation did France beat in the 1998 World Cup final?", ["Brazil", "Italy", "Croatia", "Netherlands"], 0),
    makeQ("Which nation won the Confederations Cup in 2013?", ["Spain", "Brazil", "Italy", "Uruguay"], 1),
    makeQ("Who scored Germany's winning goal in the Euro 1996 final?", ["Jurgen Klinsmann", "Oliver Bierhoff", "Matthias Sammer", "Stefan Kuntz"], 1),
    makeQ("Which nation did Portugal beat to win Euro 2016?", ["Germany", "France", "Spain", "Belgium"], 1),
    makeQ("Who scored Portugal's winning goal in the Euro 2016 final?", ["Cristiano Ronaldo", "Nani", "Eder", "Joao Mario"], 2),
    makeQ("Which nation won the 2004 UEFA European Championship?", ["Portugal", "Greece", "Czech Republic", "France"], 1),
    makeQ("Which club won the 1999 UEFA Champions League final in stoppage time?", ["Bayern Munich", "Manchester United", "Juventus", "Milan"], 1),
    makeQ("Which two clubs played the 2005 Champions League final in Istanbul?", ["Barcelona and Arsenal", "Liverpool and Milan", "Chelsea and Liverpool", "Real Madrid and Valencia"], 1),
    makeQ("Who scored the famous volley for Real Madrid in the 2002 Champions League final?", ["Raul", "Luis Figo", "Zinedine Zidane", "Roberto Carlos"], 2),
    makeQ("Which nation won the 1982 World Cup Golden Ball through Paolo Rossi's rise?", ["Italy", "Brazil", "West Germany", "Poland"], 0),
    makeQ("Which nation reached the 1958 World Cup final against Brazil?", ["France", "West Germany", "Sweden", "Wales"], 2),
    makeQ("Who scored for Argentina in the 1986 World Cup final against West Germany?", ["Diego Maradona", "Jorge Burruchaga", "Jorge Valdano", "Both B and C"], 3),
    makeQ("Which nation won the 1930 Olympic football tournament before the first World Cup era title?", ["Argentina", "Uruguay", "Italy", "Hungary"], 1),
    makeQ("Which nation won the 1960 inaugural European Championship?", ["Soviet Union", "Yugoslavia", "Spain", "France"], 0),
    makeQ("Who was known as 'Der Kaiser'?", ["Gerd Muller", "Franz Beckenbauer", "Lothar Matthaus", "Sepp Maier"], 1),
    makeQ("Which player scored the winner for Iniesta's Barcelona in the 2009 Champions League semifinal at Stamford Bridge? Trick question.", ["Iniesta scored it for Barcelona", "Messi scored it", "Eto'o scored it", "No winner was scored"], 0),
    makeQ("Which nation won the 1972 UEFA European Championship?", ["Soviet Union", "West Germany", "Belgium", "Hungary"], 1),
    makeQ("Who won the Ballon d'Or in 1995, becoming the first African winner?", ["George Weah", "Abedi Pele", "Roger Milla", "Samuel Eto'o"], 0),
    makeQ("Which nation did Cameroon defeat in the opening match of the 1990 World Cup?", ["Brazil", "Argentina", "Romania", "Soviet Union"], 1),
    makeQ("Who scored for the Netherlands in the 1988 Euro final?", ["Ruud Gullit and Marco van Basten", "Frank Rijkaard and Ronald Koeman", "Van Basten and Koeman", "Gullit and Rijkaard"], 0),
    makeQ("Which nation won the 1964 European Championship?", ["Spain", "Soviet Union", "Hungary", "Italy"], 0),
    makeQ("Which club did Johan Cruyff make famous with 'Total Football' as a player?", ["PSV", "Ajax", "Feyenoord", "AZ"], 1),
    makeQ("Who scored the golden goal in the 1998 World Cup round of 16 between France and Paraguay?", ["David Trezeguet", "Laurent Blanc", "Thierry Henry", "Zinedine Zidane"], 1),
    makeQ("Which nation beat the Netherlands in the 2010 World Cup final?", ["Germany", "Spain", "Brazil", "Uruguay"], 1),
    makeQ("Who scored the equalizer for Italy in the Euro 2020 final?", ["Federico Chiesa", "Leonardo Bonucci", "Lorenzo Insigne", "Jorginho"], 1),
    makeQ("Which nation won the 2023 Africa Cup of Nations, played in 2024?", ["Nigeria", "Ivory Coast", "Senegal", "Morocco"], 1),
    makeQ("Which nation won the 2024 Copa Libertadores?", ["Botafogo", "Atletico Mineiro", "River Plate", "Flamengo"], 0),
    makeQ("Which nation did Brazil defeat in the 1970 World Cup final?", ["Italy", "England", "Uruguay", "West Germany"], 0),
    makeQ("Who scored the winner for Manchester United in the 1999 Champions League final?", ["Teddy Sheringham", "Ole Gunnar Solskjaer", "David Beckham", "Dwight Yorke"], 1),
    makeQ("Which nation won the men's Olympic football gold in 2016?", ["Brazil", "Germany", "Argentina", "Nigeria"], 0),
    makeQ("Which country hosted the 1962 FIFA World Cup?", ["Argentina", "Chile", "Brazil", "Uruguay"], 1),
    makeQ("Who scored the decisive goal in the 1950 World Cup match remembered as the Maracanazo?", ["Juan Schiaffino", "Alcides Ghiggia", "Obdulio Varela", "Julio Perez"], 1),
    makeQ("Which player won the 1994 World Cup Golden Ball?", ["Roberto Baggio", "Romario", "Dunga", "Bebeto"], 1),
    makeQ("Which nation won the 1991 inaugural Women's World Cup?", ["Germany", "Norway", "United States", "Sweden"], 2),
    makeQ("Which nation won the Women's World Cup in 1999?", ["China", "United States", "Norway", "Germany"], 1),
    makeQ("Which nation won the Women's World Cup in 2019?", ["United States", "Netherlands", "Sweden", "England"], 0),
    makeQ("Who scored the only goal in the 2019 Women's World Cup final?", ["Megan Rapinoe", "Rose Lavelle", "Alex Morgan", "Julie Ertz"], 1),
    makeQ("Which nation did Japan beat in the 2011 Women's World Cup final?", ["Germany", "Brazil", "United States", "Sweden"], 2),
    makeQ("Which nation won the 2007 Copa America?", ["Argentina", "Brazil", "Chile", "Uruguay"], 1),
    makeQ("Who was the top scorer of the 1998 World Cup?", ["Ronaldo", "Davor Suker", "Gabriel Batistuta", "Christian Vieri"], 1),
    makeQ("Which nation won the 2001 Copa America?", ["Colombia", "Mexico", "Brazil", "Argentina"], 0),
    makeQ("Which nation won the 1987 Copa America?", ["Chile", "Uruguay", "Argentina", "Brazil"], 1),
    makeQ("Which nation won the 1995 Copa America?", ["Brazil", "Uruguay", "Argentina", "Colombia"], 1),
    makeQ("Which team did Arsenal defeat in the Women's Champions League final of 2025?", ["Barcelona", "Lyon", "Chelsea", "Wolfsburg"], 0),
    makeQ("Which nation won Euro 2022 in women's football?", ["England", "Germany", "Spain", "Sweden"], 0),
    makeQ("Who scored the fastest hat-trick in World Cup history?", ["Laszlo Kiss", "Sandor Kocsis", "Just Fontaine", "Oleg Salenko"], 0),
    makeQ("Which player holds the record for most international caps in men's football?", ["Cristiano Ronaldo", "Sergio Ramos", "Ahmed Hassan", "Bader Al-Mutawa"], 3),
    makeQ("What was the final score of the 'Match of the Century' in 1970 World Cup semifinal?", ["4-3 to Italy", "3-2 to West Germany", "4-2 to Brazil", "3-1 to Italy"], 0),
    makeQ("Which nation eliminated defending champions France in the 2022 World Cup group stage?", ["Australia", "Denmark", "Tunisia", "None - France advanced"], 3),
    makeQ("Who scored the winning penalty in the 2006 World Cup final shootout?", ["Fabio Grosso", "Andrea Pirlo", "Daniele De Rossi", "Alessandro Del Piero"], 0),
    makeQ("Which goalkeeper holds the record for longest unbeaten streak in World Cup history?", ["Gianluigi Buffon", "Walter Zenga", "Thibaut Courtois", "Iker Casillas"], 1),
    makeQ("Who was the youngest player to score in a World Cup final?", ["Pele", "Kylian Mbappe", "Michael Owen", "Diego Maradona"], 0),
    makeQ("Which club won the 2004 UEFA Champions League as massive underdogs?", ["Porto", "Monaco", "AC Milan", "Chelsea"], 0),
    makeQ("Who managed Porto to the 2004 Champions League title?", ["Jose Mourinho", "Carlo Ancelotti", "Rafa Benitez", "Guus Hiddink"], 0),
    makeQ("Which nation scored the most goals in a single World Cup tournament?", ["Hungary 1954", "Brazil 1970", "West Germany 1954", "France 1998"], 0),
    makeQ("Who scored the famous bicycle kick goal against Mexico in the 2018 World Cup?", ["Cristiano Ronaldo", "Javier Hernandez", "Edson Alvarez", "None - no bicycle kick goal"], 0),
    makeQ("Which player won the Puskas Award for best goal in 2024?", ["Vinicius Junior", "Lionel Messi", "Cristiano Ronaldo", "Kylian Mbappe"], 0),
    makeQ("What is the 'Tiki-taka' style of play most associated with?", ["Spain and Barcelona", "Germany and Bayern", "Brazil and Santos", "Italy and Juventus"], 0),
    makeQ("Which nation won the first FIFA U-20 World Cup in 1977?", ["Brazil", "Soviet Union", "Argentina", "Uruguay"], 1),
  ]
};
